#!/bin/bash

type="$1"


if [ ! -n "$type" ]
then
	clear

echo "
   ___ 
  / _ Unner
 / , _/
/_/|_| Artisan 0.1

C : Arikun-IndoSec       
==================

"
else
clear	
echo "
   ___ 
  / _ Unner
 / , _/
/_/|_| Artisan 0.1
       
C : Arikun-IndoSec
=================="
php artisan $1 $2
fi